version: '3.7'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: ./backend/prisma
      dockerfile: Dockerfile
    environment:
      APP_DB_ADDRESS: ${APP_DB_ADDRESS}
      POSTGRESQL_URL: postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@${APP_DB_ADDRESS}:5432/blog?schema=blog&sslmode=prefer
    depends_on:
      - postgress
    networks:
      gbmpsy-network: