version: '3.7'
services:
  db:
    container_name: ${APP_DB_ADDRESS}
    hostname: ${APP_DB_ADDRESS}
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASSWORD}
    networks:
      gbmpsy-network:
    ports:
      - '${APP_DB_PORT}:3306'
    volumes:
      - app-db-data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '7000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwo${APP_DB_ROOT_PASSWORD}rd 
    networks:
      gbmpsy-network:

volumes:
  app-db-data: