version: '3.7'

services:
    # Frontend
    web:
        image: jitsi/web
        ports:
            - '${HTTP_PORT}:80'
        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/web/letsencrypt:/etc/letsencrypt:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
        environment:
            - ENABLE_AUTH=${ENABLE_AUTH}
            - ENABLE_GUESTS=${ENABLE_GUESTS}
            - ENABLE_LETSENCRYPT=${ENABLE_LETSENCRYPT}
            - ENABLE_HTTP_REDIRECT=${ENABLE_HTTP_REDIRECT}
            - ENABLE_TRANSCRIPTIONS=${ENABLE_TRANSCRIPTIONS}
            - DISABLE_HTTPS=${DISABLE_HTTPS}
            - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - PUBLIC_URL=${APP_JITSI_PUBLIC_URL}
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_BOSH_URL_BASE=${XMPP_BOSH_URL_BASE}
            - XMPP_GUEST_DOMAIN=${XMPP_GUEST_DOMAIN}
            - XMPP_MUC_DOMAIN=${XMPP_MUC_DOMAIN}
            - XMPP_RECORDER_DOMAIN=${XMPP_RECORDER_DOMAIN}
            - ETHERPAD_URL_BASE=${ETHERPAD_URL_BASE}
            - TZ=${TZ}
            - JIBRI_BREWERY_MUC=${JIBRI_BREWERY_MUC}
            - JIBRI_PENDING_TIMEOUT=${JIBRI_PENDING_TIMEOUT}
            - JIBRI_XMPP_USER=${JIBRI_XMPP_USER}
            - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD}
            - JIBRI_RECORDER_USER=${JIBRI_RECORDER_USER}
            - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD}
            - ENABLE_RECORDING=${ENABLE_RECORDING}
        networks:
            gbmpsy-network:
                aliases:
                    - ${XMPP_DOMAIN}

    # XMPP server
    prosody:
        image: jitsi/prosody
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody/config:/config:Z
            - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
        environment:
            - AUTH_TYPE=${AUTH_TYPE}
            - ENABLE_AUTH=${ENABLE_AUTH}
            - ENABLE_GUESTS=${ENABLE_GUESTS}
            - GLOBAL_MODULES=${GLOBAL_MODULES}
            - GLOBAL_CONFIG=${GLOBAL_CONFIG}
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_GUEST_DOMAIN=${XMPP_GUEST_DOMAIN}
            - XMPP_MUC_DOMAIN=${XMPP_MUC_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=${XMPP_INTERNAL_MUC_DOMAIN}
            - XMPP_MODULES=${XMPP_MODULES}
            - XMPP_MUC_MODULES=${XMPP_MUC_MODULES}
            - XMPP_INTERNAL_MUC_MODULES=${XMPP_INTERNAL_MUC_MODULES}
            - XMPP_RECORDER_DOMAIN=${XMPP_RECORDER_DOMAIN}
            - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
            - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
            - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
            - JVB_AUTH_USER==${JVB_AUTH_USER}
            - JVB_AUTH_PASSWORD==${JVB_AUTH_PASSWORD}
            - JIGASI_XMPP_USER=${JIGASI_XMPP_USER}
            - JIGASI_XMPP_PASSWORD=${JIGASI_XMPP_PASSWORD}
            - JIBRI_XMPP_USER=${JIBRI_XMPP_USER}
            - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD}
            - JIBRI_RECORDER_USER=${JIBRI_RECORDER_USER}
            - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD}
            - JWT_APP_ID={APP_JITSI_JWT_APP_ID}
            - JWT_APP_SECRET=${APP_JITSI_JWT_APP_SECRET}
            - JWT_ACCEPTED_ISSUERS=${JWT_ACCEPTED_ISSUERS}
            - JWT_ACCEPTED_AUDIENCES=${JWT_ACCEPTED_AUDIENCES}
            - JWT_ASAP_KEYSERVER=${JWT_ASAP_KEYSERVER}
            - JWT_ALLOW_EMPTY=${JWT_ALLOW_EMPTY}
            - JWT_AUTH_TYPE=${JWT_AUTH_TYPE}
            - JWT_TOKEN_AUTH_MODULE=${JWT_TOKEN_AUTH_MODULE}
            - LOG_LEVEL=${LOG_LEVEL}
            - TZ=${TZ}
        networks:
            gbmpsy-network:
                aliases:
                    - ${XMPP_SERVER}

    # Focus component
    jicofo:
        image: jitsi/jicofo
        volumes:
            - ${CONFIG}/jicofo:/config:Z
        environment:
            - ENABLE_AUTH=${ENABLE_AUTH}
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=${XMPP_INTERNAL_MUC_DOMAIN}
            - XMPP_SERVER=${XMPP_SERVER}
            - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
            - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
            - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
            - JICOFO_RESERVATION_REST_BASE_URL=${JICOFO_RESERVATION_REST_BASE_URL}
            - JVB_BREWERY_MUC=${JVB_BREWERY_MUC}
            - JIGASI_BREWERY_MUC=${JIGASI_BREWERY_MUC}
            - JIGASI_SIP_URI=${JIGASI_SIP_URI}
            - JIBRI_BREWERY_MUC=${JIBRI_BREWERY_MUC}
            - JIBRI_PENDING_TIMEOUT=${JIBRI_PENDING_TIMEOUT}
            - TZ=${TZ}
        depends_on:
            - prosody
        networks:
            gbmpsy-network:

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_MAPPED_PORT}:${JVB_TCP_PORT}'
        volumes:
            - ${CONFIG}/jvb:/config:Z
        environment:
            - DOCKER_HOST_ADDRESS=${DOCKER_HOST_ADDRESS}
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=${XMPP_INTERNAL_MUC_DOMAIN}
            - XMPP_SERVER=${XMPP_SERVER}
            - JVB_AUTH_USER=${JVB_AUTH_USER}
            - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
            - JVB_BREWERY_MUC=${JVB_BREWERY_MUC}
            - JVB_PORT=${JVB_PORT}
            - JVB_TCP_HARVESTER_DISABLED=${JVB_TCP_HARVESTER_DISABLED}
            - JVB_TCP_PORT=${JVB_TCP_PORT}
            - JVB_STUN_SERVERS=${JVB_STUN_SERVERS}
            - JVB_ENABLE_APIS=${JVB_ENABLE_APIS}
            - TZ=${TZ}
        depends_on:
            - prosody
        networks:
            gbmpsy-network:
